2018-01-24 12:31:48,863 ERROR: Exception on /explore [GET] [in /Users/lydiding/Desktop/microblog/venv/lib/python3.6/site-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/Users/lydiding/Desktop/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/lydiding/Desktop/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/lydiding/Desktop/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/lydiding/Desktop/microblog/venv/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/Users/lydiding/Desktop/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/lydiding/Desktop/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/lydiding/Desktop/microblog/venv/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/Users/lydiding/Desktop/microblog/app/routes.py", line 63, in explore
    return render_template("index.html", title = "Explore", form = form,
NameError: name 'form' is not defined
2018-01-24 12:31:51,106 ERROR: Exception on /explore [GET] [in /Users/lydiding/Desktop/microblog/venv/lib/python3.6/site-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/Users/lydiding/Desktop/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/lydiding/Desktop/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/lydiding/Desktop/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/lydiding/Desktop/microblog/venv/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/Users/lydiding/Desktop/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/lydiding/Desktop/microblog/venv/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/lydiding/Desktop/microblog/venv/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/Users/lydiding/Desktop/microblog/app/routes.py", line 63, in explore
    return render_template("index.html", title = "Explore", form = form,
NameError: name 'form' is not defined
2018-01-24 12:32:19,205 INFO: Microblog startup [in /Users/lydiding/Desktop/microblog/app/__init__.py:75]
2018-01-24 14:25:20,316 INFO: Microblog startup [in /Users/lydiding/Desktop/microblog/app/__init__.py:75]
2018-01-24 14:32:12,587 INFO: Microblog startup [in /Users/lydiding/Desktop/microblog/app/__init__.py:75]
